name: Generate Docs

on:
  repository_dispatch:
    types: [ generate-docs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Clean
      run: ./build.sh clean

    - name: Generate
      run: ./build.sh generate

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Documentation generated
        branch: master
        file_pattern: docs/